name: Test

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: "Test project"
      uses: pyrmont/action-janet-test@v2
